//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/ethernet/edgeserver/ENComputationOffloading.msg.
//

#ifndef __INET_ENCOMPUTATIONOFFLOADING_M_H
#define __INET_ENCOMPUTATIONOFFLOADING_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ENCOReq;
class ENCOResp;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/ethernet/edgeserver/ENComputationOffloading.msg:23</tt> by nedtool.
 * <pre>
 * class ENCOReq extends FieldsChunk
 * {
 *     long requestId;
 *     long responseBytes;
 *     int hello;
 * }
 * </pre>
 */
class INET_API ENCOReq : public ::inet::FieldsChunk
{
  protected:
    long requestId = 0;
    long responseBytes = 0;
    int hello = 0;

  private:
    void copy(const ENCOReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ENCOReq&);

  public:
    ENCOReq();
    ENCOReq(const ENCOReq& other);
    virtual ~ENCOReq();
    ENCOReq& operator=(const ENCOReq& other);
    virtual ENCOReq *dup() const override {return new ENCOReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual long getRequestId() const;
    virtual void setRequestId(long requestId);
    virtual long getResponseBytes() const;
    virtual void setResponseBytes(long responseBytes);
    virtual int getHello() const;
    virtual void setHello(int hello);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ENCOReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ENCOReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/applications/ethernet/edgeserver/ENComputationOffloading.msg:30</tt> by nedtool.
 * <pre>
 * class ENCOResp extends FieldsChunk
 * {
 *     int requestId;
 *     int numFrames;
 *     int hello;
 * }
 * </pre>
 */
class INET_API ENCOResp : public ::inet::FieldsChunk
{
  protected:
    int requestId = 0;
    int numFrames = 0;
    int hello = 0;

  private:
    void copy(const ENCOResp& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ENCOResp&);

  public:
    ENCOResp();
    ENCOResp(const ENCOResp& other);
    virtual ~ENCOResp();
    ENCOResp& operator=(const ENCOResp& other);
    virtual ENCOResp *dup() const override {return new ENCOResp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);
    virtual int getNumFrames() const;
    virtual void setNumFrames(int numFrames);
    virtual int getHello() const;
    virtual void setHello(int hello);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ENCOResp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ENCOResp& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_ENCOMPUTATIONOFFLOADING_M_H

