/*
 * MyEthernetMsg.h
 *
 *  Created on: 2021. 4. 8.
 *      Author: bum71
 */

#ifndef INET_APPLICATIONS_ETHERNET_MYETHERNETEXAMPLE_MYETHERNETMSGTYPE_H_
#define INET_APPLICATIONS_ETHERNET_MYETHERNETEXAMPLE_MYETHERNETMSGTYPE_H_

enum MyEthernetMsgType{
    ES_AVAILABILITY_REQ=123,
    ES_AVAILABILITY_RESP,
    OFFLOADING_REQ,
    OFFLOADING_RESP,
    MYMSG_REQ,
    MYMSG_RESP
};



#endif /* INET_APPLICATIONS_ETHERNET_MYETHERNETEXAMPLE_MYETHERNETMSGTYPE_H_ */
